### ISSUE TITLE
It will automatically jump to agar.io

### ISSUE THREAD

**Issue by hcyxsq** [ibash/agar#1]
when I type "http://localhost:8888", then it will jump to the orginal agar.io page, how to solve it?

**Comment by cooljddj** [comment]
bc there is a part of the js that redirects to it

**Comment by hcyxsq** [comment]
but why the javascript redirects the browser to origin agar.io page?

**Comment by ibash** [comment]
That shouldn't happen, the code that redirects explicitly allows using localhost:
```
    if ("agar.io" != f.location.hostname && "localhost" != f.location.hostname && "10.10.2.13" != f.location.hostname) f.location = F + "//agar.io/";
```

Two things to try:

1. Try clearing your browser cache

2. Change some code in `public/main_out.js`

Find this code in `public/main_out.js`:
```
    if ("agar.io" != f.location.hostname && "localhost" != f.location.hostname && "10.10.2.13" != f.location.hostname) f.location = F + "//agar.io/";
    else if (f.top != f) f.top.location = F + "//agar.io/";
    else {
```

and change it to just:
```
    if (true)  {
```

**Comment by hcyxsq** [comment]
okay I'll try it later,thanks.
