### ISSUE TITLE
Referencing issue with "ml-js"

### ISSUE THREAD

**Issue by TopGunSnake** [ibash/agar#3]
Have you implemented the ml-js library?

**Comment by ibash** [comment]
What do you mean by implemented the ml-js library?

**Comment by TopGunSnake** [comment]
This is my first time directly using Node.js, but on the agar-training branch, it seems the .json file references a library local to your machine, "ibash/ml-js".

**Comment by ibash** [comment]
That should be fine, if you do `npm install` it should install the dependency from github. But before you do that checkout the readme on ml-js, there's a few dependencies outside of npm you need to install.



Islam Sharabash217-377-9657
