### ISSUE TITLE
It's possible to make another custom client with working server from agar.io servers?

### ISSUE THREAD

**Issue by Tekameikite** [ibash/agar#5]
Your project is really good but i want to make something like custom client with servers from agar.io.
Such as agario web-client with private ogar servers but with original agar.io servers.
I don't know how to prounance it in other ways (my english is bad af) :sweat_smile: :joy: :laughing: :

**Comment by Davvideo** [comment]
It's anyone here?

**Comment by ibash** [comment]
Okay, so you want a nose client with ogar servers?
